### PR TITLE
convert 9. Regular tiled backgrounds to Markdown

### LINKED ISSUE #21: Convert to mardown - regbg (Regular tiled backgrounds)

### PR DESCRIPTION
**Pull request by pinobatch**
closes #21

### CODE REVIEW

**Comment by exelotl** [comment]
Hey, this is great! Here's some things I noticed:

* "you can switch to 1D mapping by setting `REG_DISPCNT`{6}" - the {6} doesn't show up properly, I guess the markdown parser swallowed it and so it needs escaping?

* "Force alignment on OBJ_ATTRs" - this note heading is now gone, the content just appears as a regular paragraph, is that intentional? The closing `</div>` tag still seems to be there.

* There's a small typo in <`ATTR0_GFX#`  (the < shouldn't be there?)

* I think it would be best to _not_ update the register diagrams to use `<code>` for the define column (at least not at this point in time) as it will introduce inconsistency with other pages.

* Also, I noticed the heading for `OBJ_ATTR.attr0` now renders as `Table 8.3: OBJ_ATTR.attr0`, which is inconsistent with other pages, though it appears to be correct for making the table numbering match up with the original document. In other words, Tonc seems to treat bit layout diagrams as tables but doesn't show the numbers. We should probably _keep the numbers hidden for now_, but I have made an issue (https://github.com/gbadev-org/tonc/issues/34) to make sure this gets resolved later.

**Comment by pinobatch** [comment]
I'll remove `<code>` and table numbers from bit layouts. Most everything else that you mentioned appears to apply to my objects PR (#27), not this one.

**Comment by exelotl** [comment]
Yes sorry! I just realised I left this feedback on the wrong PR :sweat_smile:

Re: table numbers on bit layouts: It seems the preferred option by me and @LunarLambda is to just not use `tbl:`  IDs for those, and we'll just have to accept that the subsequent table numbers won't be the same as the original Tonc text.

However, I noticed there is one place in this chapter (regbg) which says _"The exact layout can be found in table 9.7"_ (despite there being no table labelled 9.7 on the page originally). This will need changing to "The exact layout can be found in the diagram below" or something like that.

**Comment by LunarLambda** [comment]
There is more than one place, table 9.4 is also missing a caption (notice the tables before and after being 9.3 and 9.5 respectively)

I did double check the HTML source (TONC is quite poorly written in terms of correctly adhering to HTML, for example most of the tables don't use any closing `</td>` tags), and nope, it just mentions a table that is otherwise never labeled, even in the markup

image

**Comment by pinobatch** [comment]
It's acceptable for HTML5 in HTML serialization (as opposed to XML) to lack closing `</td>` tags. Because a `<td>` element cannot exist directly inside another `<td>` element, an HTML5 parser is expected to close the element when it sees the following element's start tag.

Otherwise, I've written around the reference to table 9.4, much as with table 9.7.

**Comment by exelotl** [comment]
Sweet!

I think the one remaining thing to do on this is updating the equation (9.1) to use MathML.

Something along these lines?

```html
<table id="eq:bgr-dx" title="eq-bgr-dx">
<tbody><tr>
  <td class="eqnrcell">({!@eq:bgr-dx})</td>
  <td class="eqcell">
    <math> ..... mathml goes here ..... </math>
  </td>
</tr></tbody></table>
```

**Comment by pinobatch** [comment]
I know no MathML. Could we can save the equations for a later issue?

**Comment by exelotl** [comment]
Sure, it's not so important for this one, but I'd suggest to replace it with the original HTML as the bulleted list doesn't look so great.

If you did want to try mathml, you can use an online editor to generate it for you. It's not something you're expected to write by hand.

* https://latexeditor.lagrida.com/ - you can write latex then right-click the output and copy to clipboard as mathml
* https://webdemo.myscript.com/views/math/index.html - can generate latex or mathml via handwriting recognition

**Comment by exelotl** [comment]
Thanks!

**Pull request merged**
