### PR TITLE
Convert gfx chapter

### LINKED ISSUE #32: Convert to markdown : gfx (Graphic effects)

### PR DESCRIPTION
**Pull request by LunarLambda**
Closes #32 

Please review, I think I got everything but this file is gigantic and I had to rewrite so many things

### CODE REVIEW

**Comment by exelotl** [comment]
> \`bld_demo\` features 2 metroids

References to filenames etc. should be italic (decided [here](https://github.com/gbadev-org/tonc/pull/12#issuecomment-1708077358)) rather than using backticks. These references use `<tt>` tags in the original HTML so you can locate them that way.

> \`\`\` {#cd-bld-demo .c}

This pandoc syntax for assigning IDs to code blocks doesn't work in other .md parsers, so you gotta wrap it a div instead, like so:
  
    <div id="#cd-bld-demo" markdown>
    ```c
    code here
    ```
    </div>

Apart from those minor things it's perfect!

**Comment by LunarLambda** [comment]
Alright, will handle tomorrow

**Comment by LunarLambda** [comment]
Same fixups done as #37, will add the MathML later

**Comment by exelotl** [comment]
Thanks a bunch and sorry for the delay!

**Pull request merged**
