### PR TITLE
Convert affbg

### LINKED ISSUE #31: Convert to markdown : affbg (Affine tiled backgrounds)

### PR DESCRIPTION
**Pull request by LunarLambda**
Closes #31

### CODE REVIEW

**Comment by exelotl** [comment]
Looking good!

The same feedback as in https://github.com/gbadev-org/tonc/pull/36 applies here (use italics for places where `<tt>` was used in the original html, and wrapper divs to preserve IDs on code blocks).

> _(see table 12.1). The sizes are also different for affine backgrounds. You can find a list of sizes in table 12.2._
> ...
> _You can find their addresses in table 12.3._

These references to tables need converting into auto-references.

Also this chapter is very math-heavy, so I think converting the formulae to MathML is important.

**Comment by LunarLambda** [comment]
Gotcha, will handle all that tomorrow.

I thought the existing attribute list syntax works on code blocks? that's what pandoc spits out anyway.

**Comment by exelotl** [comment]
In python-markdown it seems to get the language but not the ID.

In mdbook it does... uh, this:

Screenshot from 2023-09-16 21-05-46

**Comment by LunarLambda** [comment]
> Looking good!
> 
> The same feedback as in #36 applies here (use italics for places where `<tt>` was used in the original html, and wrapper divs to preserve IDs on code blocks).
> 
> > _(see table 12.1). The sizes are also different for affine backgrounds. You can find a list of sizes in table 12.2._
> > ...
> > _You can find their addresses in table 12.3._
> 
> These references to tables need converting into auto-references.

All patched up now.

> Also this chapter is very math-heavy, so I think converting the formulae to MathML is important.

That's going to be a pretty significant effort (compared to the bounty), and I probably can't make it look the same as it does in the original. Should that be a separate PR?

**Pull request merged**
