### PR TITLE
convert and cleanup 5. Bitmaps

### LINKED ISSUE #11: Convert 5 - The Bitmap modes to markdown
Part of https://github.com/gbadev-org/tonc/issues/4

### PR DESCRIPTION
**Pull request by pinobatch**
figure autonumbering not yet added

closes #11

### CODE REVIEW

**Comment by exelotl** [comment]
Looks good so far!

The markdown code snippets don't seem to support anchor IDs. For those which have them ({#cd-vid-flip} and such)
I'd go with a solution like this:

    <div id="cd-vid-flip" markdown>
    
    ```c
    u16 *vid_flip()
    {
        // toggle the write_buffer's page
        vid_page= (u16*)((u32)vid_page ^ VID_FLIP);
        REG_DISPCNT ^= DCNT_PAGE;            // update control register
        return vid_page;
    }
    ```
    
    </div>

Also, I noticed that `<tt>` which was used for referring to file names has gone. I'm not really sure what to do about that one. It's not the same as code, so backticks aren't really appropriate, but maybe still useful to have filenames represented visually? I kept the `<tt>` tags it in first.md, but am open to suggestions.

**Comment by avivace** [comment]
I would suggest using italic for filenames, e.g. _mycode.c_

**Review by avivace — APPROVED** [review]
A part what mentioned by @exelotl , LGTM

**Comment by pinobatch** [comment]
Force-pushed separating the automatic steps from the manual steps.

**Review by exelotl — CHANGES_REQUESTED** [review]
This is great! Just needs figure autonumbering then we can merge :+1:

**Review by exelotl — APPROVED** [review]

**Pull request merged**
